<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
<?php if ($_shipment && $_order && $trackCollection): ?>
    <br />
    <table class="shipment-track">
        <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($trackCollection as $_item): ?>
            <tr>
                <td><?= $block->escapeHtml($_item->getTitle()) ?></td>
                <!--<td><?= $block->escapeHtml($_item->getNumber()) ?></td>  Original-Konfiguration ohne Verlinkung-->
				<td><a href="https://tracking.dpd.de/parcelstatus?query=<?php echo $_item->getNumber() ?>&locale=de_AT"><?php echo $_item->getNumber() ?></a></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif; ?>
